language: python
sudo: required
dist: xenial
install: "pip install -r requirements.txt"
matrix:
  include:
    - python: "3.6"
      env: TEST_CMD=pytest
    - python: "3.6"
      env: TEST_CMD=pylava
    - python: "3.7"
      env: TEST_CMD=pytest
    - python: "3.7"
      env: TEST_CMD=pylava
script: $TEST_CMD
